<a href="https://colab.research.google.com/github/aolivas92/tensorflow_certificate_course/blob/main/00_tensorflow_fundamentals_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 2: Deep Learning and TensorFlow Fundamentals

These are the exercises for Section 2.

In [2]:
import tensorflow as tf

## Exercise 1:
  Create a vector, scalar, matrix and tensor with values of you choosing using `tf.constant()`.

In [3]:
# Create a Scalar
scalar = tf.constant(1)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
# Create a vector
vector = tf.constant([1, 2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [5]:
# Create a matrix
matrix = tf.constant([[1, 2],
                      [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [6]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3, 4, 5],
                       [6, 7, 8, 9, 10],
                       [11, 12, 13, 14, 15]],
                      [[16, 17, 18, 19, 20],
                       [21, 22, 23, 24, 25],
                       [26, 27, 28, 29, 30]]])
tensor

<tf.Tensor: shape=(2, 3, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]], dtype=int32)>

## Exercise 2:
  Find the shape, rank and size of the tensors you created in 1

In [7]:
# Find the shape
scalar.shape, vector.shape, matrix.shape, tensor.shape

(TensorShape([]),
 TensorShape([2]),
 TensorShape([2, 2]),
 TensorShape([2, 3, 5]))

In [10]:
# Find the rank
tf.rank(scalar), tf.rank(vector), tf.rank(matrix), tf.rank(tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

## Exercise 3:
  Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [12]:
# Create a random tensor
tf.random.set_seed(10)
random_tensor = tf.random.uniform([5, 300], 0, 1, dtype=tf.float32)
random_tensor

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.644151  , 0.8082472 , 0.8976548 , ..., 0.64856505, 0.92532265,
        0.21082604],
       [0.3861388 , 0.6250967 , 0.8140892 , ..., 0.4822954 , 0.8364854 ,
        0.02696836],
       [0.01568139, 0.070153  , 0.07581997, ..., 0.03713143, 0.10203564,
        0.9430717 ],
       [0.6311755 , 0.6480881 , 0.02148747, ..., 0.8134506 , 0.1877768 ,
        0.34784198],
       [0.58412063, 0.90507317, 0.08946109, ..., 0.4087528 , 0.11643791,
        0.3630116 ]], dtype=float32)>

In [13]:
# Another random tensor
tf.random.set_seed(5)
random_tensor2 = tf.random.uniform([5, 300], 0, 1, dtype=tf.float32)
random_tensor2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6263931 , 0.5298432 , 0.7584572 , ..., 0.90544045, 0.7310214 ,
        0.90369546],
       [0.273291  , 0.20672214, 0.8453766 , ..., 0.07593   , 0.38916862,
        0.7556366 ],
       [0.26036024, 0.7548555 , 0.80566   , ..., 0.90415967, 0.90981686,
        0.7273755 ],
       [0.6264539 , 0.06932247, 0.844401  , ..., 0.6659845 , 0.5977441 ,
        0.6978576 ],
       [0.681298  , 0.74360526, 0.03553867, ..., 0.8288864 , 0.81795514,
        0.5918746 ]], dtype=float32)>

## Exercise 4:
  Multiply the two tensors you created in 3 using matrix multiplication

In [14]:
# Transpose the second tensor so that the inner shape will match
random_tensor2_transpose = tf.transpose(random_tensor2)
random_tensor.shape, random_tensor2_transpose.shape

(TensorShape([5, 300]), TensorShape([300, 5]))

In [15]:
# Perform the matrix multiplication
tf.matmul(random_tensor, random_tensor2_transpose)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[79.75633 , 72.57199 , 79.45242 , 78.387505, 78.52792 ],
       [80.81929 , 74.83064 , 79.48054 , 78.17579 , 78.90487 ],
       [80.44235 , 72.50193 , 78.26175 , 76.44103 , 76.72252 ],
       [74.99447 , 69.38485 , 72.8277  , 72.82704 , 71.779526],
       [83.671455, 75.20619 , 82.214325, 83.52528 , 82.254585]],
      dtype=float32)>

## Exercise 5:
  Multiply the two tensors you created in 3 using dot product

In [17]:
# Because both are matrices and based on the documentaton this 'should' do the same as above
tf.tensordot(random_tensor, random_tensor2_transpose, axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[79.75633 , 72.57199 , 79.45242 , 78.387505, 78.52792 ],
       [80.81929 , 74.83064 , 79.48054 , 78.17579 , 78.90487 ],
       [80.44235 , 72.50193 , 78.26175 , 76.44103 , 76.72252 ],
       [74.99447 , 69.38485 , 72.8277  , 72.82704 , 71.779526],
       [83.671455, 75.20619 , 82.214325, 83.52528 , 82.254585]],
      dtype=float32)>

## Exercise 6:
  Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [27]:
# Create a random tensor with the shape given above
tf.random.set_seed(18)
random_tensor = tf.random.uniform([224, 224, 3], 0, 1, dtype=tf.float32)
random_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.99482024, 0.423509  , 0.23757601],
        [0.8386767 , 0.27640712, 0.87007296],
        [0.35700917, 0.33393836, 0.16027129],
        ...,
        [0.17754447, 0.5713713 , 0.97352743],
        [0.7309836 , 0.58929574, 0.16528249],
        [0.35416794, 0.38309777, 0.766881  ]],

       [[0.01335502, 0.41415703, 0.13315153],
        [0.25568032, 0.9836961 , 0.09868717],
        [0.44091976, 0.9660728 , 0.33621168],
        ...,
        [0.9087516 , 0.5766876 , 0.9477968 ],
        [0.9579953 , 0.31321037, 0.15659821],
        [0.12257206, 0.808882  , 0.28059757]],

       [[0.6214088 , 0.15641761, 0.37106526],
        [0.80857825, 0.20923662, 0.7185221 ],
        [0.320431  , 0.8950213 , 0.5877565 ],
        ...,
        [0.08209133, 0.01587713, 0.79199886],
        [0.81192684, 0.16580105, 0.38367558],
        [0.24895954, 0.29836333, 0.75185513]],

       ...,

       [[0.30067873, 0.29766667, 0.20861435],
        [0.85

## Exercise 7:
  Find the min and max values of the tensor you created in 6 along the first axis

In [28]:
# Find the min of the tensor
tf.reduce_min(random_tensor,axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[7.49814510e-03, 1.34546757e-02, 3.17740440e-03],
       [5.74946404e-04, 2.86328793e-03, 6.56747818e-03],
       [2.19583511e-03, 1.58771276e-02, 8.02814960e-03],
       [1.83713436e-03, 1.36542320e-03, 2.90060043e-03],
       [5.39004803e-03, 7.29513168e-03, 4.97198105e-03],
       [1.39659643e-02, 1.26123428e-04, 7.85136223e-03],
       [5.39779663e-04, 7.42161274e-03, 9.30905342e-04],
       [3.25632095e-03, 8.65459442e-04, 1.55260563e-02],
       [6.32011890e-03, 6.85858727e-03, 4.52971458e-03],
       [2.76041031e-03, 3.32546234e-03, 3.33786011e-04],
       [6.96194172e-03, 1.41791105e-02, 3.55255604e-03],
       [9.59324837e-03, 4.04715538e-04, 2.63059139e-03],
       [9.55581665e-04, 5.78165054e-05, 2.81941891e-03],
       [3.18300724e-03, 1.35768652e-02, 3.66330147e-04],
       [4.93729115e-03, 3.59904766e-03, 5.22732735e-04],
       [3.40163708e-03, 1.45792961e-03, 4.24051285e-03],
       [1.74338818e-02, 1.59978867e-03

In [26]:
tf.reduce_max(random_tensor, axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.9977789 , 0.9858761 , 0.9978678 ],
       [0.999171  , 0.99511325, 0.9973055 ],
       [0.99424577, 0.9894004 , 0.9960723 ],
       [0.9973507 , 0.99884427, 0.99143755],
       [0.99767196, 0.99292684, 0.9993422 ],
       [0.9955162 , 0.98788345, 0.99345136],
       [0.9926443 , 0.988819  , 0.99653375],
       [0.9951502 , 0.99374247, 0.99498665],
       [0.9997071 , 0.9995707 , 0.99792445],
       [0.9996495 , 0.9936725 , 0.9991207 ],
       [0.9889709 , 0.995986  , 0.9991149 ],
       [0.9983127 , 0.9927676 , 0.98944736],
       [0.9979882 , 0.99528146, 0.99316084],
       [0.9837713 , 0.99908245, 0.9987407 ],
       [0.9977478 , 0.992502  , 0.99731743],
       [0.9999981 , 0.999215  , 0.9998152 ],
       [0.99773335, 0.9989116 , 0.9981301 ],
       [0.9879352 , 0.9989314 , 0.9998864 ],
       [0.99861455, 0.99682915, 0.9977082 ],
       [0.9988116 , 0.9996662 , 0.99333286],
       [0.9866288 , 0.9827758 , 0.9972521 ],
     

## Exercise 8:
  Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [29]:
# Create a random tensor
tf.random.set_seed(10)
random_tensor = tf.random.uniform([1, 224, 224, 3], 0, 10)
random_tensor

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[6.4415097 , 8.082472  , 8.976547  ],
         [6.3689017 , 6.270969  , 9.936013  ],
         [0.23594856, 0.36683917, 5.8605776 ],
         ...,
         [4.021759  , 8.761731  , 8.2401905 ],
         [5.633031  , 2.6415741 , 5.9228563 ],
         [1.0286665 , 5.3559933 , 7.9840636 ]],

        [[6.234499  , 5.6968355 , 4.731779  ],
         [4.444275  , 2.0357692 , 3.325795  ],
         [6.534798  , 3.7811399 , 1.1533725 ],
         ...,
         [5.544293  , 2.0996773 , 1.3778448 ],
         [2.790662  , 6.5291204 , 7.396562  ],
         [3.0591393 , 7.044697  , 7.4819875 ]],

        [[2.532823  , 4.2836895 , 4.3761683 ],
         [0.07778049, 6.6289473 , 0.16618967],
         [8.85396   , 5.4001713 , 0.6657803 ],
         ...,
         [7.9703116 , 8.331604  , 0.5939698 ],
         [6.0773554 , 3.0967402 , 5.5589724 ],
         [4.2352953 , 6.156369  , 5.3281474 ]],

        ...,

        [[3.9041972 , 2.9344285 , 

In [31]:
random_tensor_squeezed = tf.squeeze(random_tensor)
random_tensor_squeezed

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[6.4415097 , 8.082472  , 8.976547  ],
        [6.3689017 , 6.270969  , 9.936013  ],
        [0.23594856, 0.36683917, 5.8605776 ],
        ...,
        [4.021759  , 8.761731  , 8.2401905 ],
        [5.633031  , 2.6415741 , 5.9228563 ],
        [1.0286665 , 5.3559933 , 7.9840636 ]],

       [[6.234499  , 5.6968355 , 4.731779  ],
        [4.444275  , 2.0357692 , 3.325795  ],
        [6.534798  , 3.7811399 , 1.1533725 ],
        ...,
        [5.544293  , 2.0996773 , 1.3778448 ],
        [2.790662  , 6.5291204 , 7.396562  ],
        [3.0591393 , 7.044697  , 7.4819875 ]],

       [[2.532823  , 4.2836895 , 4.3761683 ],
        [0.07778049, 6.6289473 , 0.16618967],
        [8.85396   , 5.4001713 , 0.6657803 ],
        ...,
        [7.9703116 , 8.331604  , 0.5939698 ],
        [6.0773554 , 3.0967402 , 5.5589724 ],
        [4.2352953 , 6.156369  , 5.3281474 ]],

       ...,

       [[3.9041972 , 2.9344285 , 6.9989195 ],
        [4.63

## Exercise 9:
  Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [35]:
# Create a random tensor
tf.random.set_seed(15)
random_tensor = tf.random.uniform([10], 0, 20, dtype=tf.int32)
random_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 7, 12, 18,  4,  8,  7, 19, 15,  1,  8], dtype=int32)>

In [39]:
tf.argmax(random_tensor), random_tensor[tf.argmax(random_tensor)], tf.reduce_max(random_tensor)

(<tf.Tensor: shape=(), dtype=int64, numpy=6>,
 <tf.Tensor: shape=(), dtype=int32, numpy=19>,
 <tf.Tensor: shape=(), dtype=int32, numpy=19>)

## Exercise 10:
  One-hot encode a tensor

In [43]:
# Create a new tensor
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [44]:
# One_hot encode our tensor
tf.one_hot(tensor, 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>